backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles:
    - admin
    - show_notes

media_folder: "images/uploads"

collections:
  - name: "js-jabber" # Used in routes, e.g., /admin/collections/blog
    label: "JavaScript Jabber" # Used in the UI
    folder: "src/js-jabber" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Podcast", name: "podcast", widget: "hidden", default: "js-jabber"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Episode Number", name: "episode_number", widget: "string"}
      - {label: "Duration", name: "duration", widget: "string"}
      - {label: "Audio URL", name: "audio_url", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list", default: ["views-on-vue", "podcast"] }
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["charles-max-wood"], default: "charles-max-wood"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list", default: ["blog"]}
      - {label: "Body", name: "body", widget: "markdown"}