backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["charles-max-wood"], default: "charles-max-wood"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Episode Number (format 001)", name: "episode_number", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", }
      - {label: "Body", name: "body", widget: "markdown"}